### ISSUE TITLE
The new service tooltips contradict actual default values

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/mintupload#10]
OS: Mint 16 "Petra" 32-bit
mintUpload 3.9.4

While creating a new service, tooltips could help, but the displayed domain and user name are not what the tooltips suggest.

Host name
Tooltip: mint-space.com
Actual text in text box: hostname.com

User name
Tooltip: it says it's your local user name
Actual text in text box: username

Also related, the password tooltip might be confusing considering the default port and service are 21/FTP.

The password tooltip is: "Password, by default: password-less SCP connection, null-string FTP connection, ~/.ssh keys used for SFTP connections"

and it should be: "Password, by default: null-string FTP connection, password-less SCP connection, ~/.ssh keys used for SFTP connections"

If the tooltip mentions SCP first you will have doubts whether by default mintUpload will try SCP or FTP.

Nag: "Timestamp format (strftime). By default:" <- this should have a trailing space :P

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/mintupload/commit/634a3d5fe7d6970035683efc4bd37e7753bc2650
