### ISSUE TITLE
Translation: Time strings need to be fetched with ngettext

### ISSUE THREAD

**Issue by gunchleoc** [linuxmint/mintupload#20]
The following time strings need to be fetched with ngettext:

```
%(hours)d hours, %(minutes)d minutes

1 hour, %d minutes

%(minutes)d minutes, %(seconds)d seconds

1 minute, %d seconds

%d seconds
```

Located starting from: usr/lib/linuxmint/mintUpload/mintUpload.py:191

Since most of these contain 2 numbers, maybe the following design would work:

```
%(hours)d hours, %(minutes)s
```

Combined with:

```
%(minutes)d minutes
```

And

```
%(minutes)d minutes, %(seconds)s
```

Combined with:

```
%(seconds)d seconds
```

**Comment by NikoKrause** [comment]
PR created
