### ISSUE TITLE
Multiple icons in panel

### ISSUE THREAD

**Issue by ghost** [linuxmint/mintupload#23]
**What happens**: run MintUpload (via any route, I think). Close it. Run it again. Close again. Result: two MintUpload icons in my panel. Indeed one can generate three icons in this manner.

**What should happen**: either the icon should disappear when one quits the program, or, if not, only one icon should ever appear at any one time. Presumably!

_This problem is similar to two others_ that have been reported (see https://github.com/linuxmint/mintupload/issues/5 and https://github.com/linuxmint/mintupload/issues/4)

Mint 17.3 x64 Cinnamon 2.8.8.

**Comment by tiwari85aman** [comment]
@ACinnamonUserInUK  I would like to take over this issue, please give me some roadmap to get directly to the issue code part.

**Comment by ACinnamonUserInUK** [comment]
@tiwari85aman 

> I would like to take over this issue

Sounds good.

>  please give me some roadmap to get directly to the issue code part.

I am afraid that I do not understand. Do you mean you want to be pointed to the bit of the Mint code that is problematic? If so, I can't easily help you there, for I am not a Mint developer and indeed I am not even much of a programmer.

**Comment by tiwari85aman** [comment]
@ACinnamonUserInUK No Problem! I will go through it myself.

**Comment by tiwari85aman** [comment]
@ACinnamonUserInUK  Sir, I have fixed issue #5 and hence on clicking on "Quit" option from tray icon will close the running "upload-manager".

**Comment by ACinnamonUserInUK** [comment]
Good! Well done. I have not tested your fix (and cannot do so easily) but if you are confident that you have indeed fixed the problem, then you or I can close this issue.

**Comment by tiwari85aman** [comment]
I am working on #23 and #4 and will fix those issues also, But for now only #5 is solved.
