### ISSUE TITLE
hardcoded icon for mintupload

### ISSUE THREAD

**Issue by erikdubois** [linuxmint/mintupload#25]
In usr/share/applications/mintupload.desktop 
you are using an hardcoded path to the icon.
result it will not change if you are choosing an other theme and it breaks the beauty of your theme.

please change the following code 

Exec=mintupload-manager
**Icon=/usr/share/pixmaps/mintupload/icon.svg**
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Application;System;Settings
StartupNotify=false
NotShowIn=KDE;

to

Exec=mintupload-manager
**Icon=mintupload**
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Application;System;Settings
StartupNotify=false
NotShowIn=KDE;

**Comment by erikdubois** [comment]
Could you please change these hardcoded icons?
Only two icons of linux mint are still hardcoded.
1.mintbackup
2. uploadmanager

I will make a seperate post for either of them.

An image is worth a thousand words. Theme looks great...apart from two mint icons.

![mint-hardcoded-icons](https://cloud.githubusercontent.com/assets/10594806/18834757/00f7fc1a-83f8-11e6-8b77-346ddb5320c7.gif)

**Comment by erikdubois** [comment]
I am testing Linux Mint 18.1 Cinnamon
The hardcoded icons is still there and it is the ONLY ONE that breaks the otherwise great look.

Icon=/usr/share/pixmaps/mintupload/icon.svg

**Comment by erikdubois** [comment]
I just received a new update of your application but the issue is still not resolved.
Could you please get rid of the hardcoded link to the icon?
thanks

**Comment by theel0ja** [comment]
Any fix to this?

**Comment by erikdubois** [comment]
Use the hardcodefixer.sh script on 
Github.com/erikdubois
Take operating system you have or any other

**Comment by theel0ja** [comment]
#32 fixed this.

**Comment by erikdubois** [comment]
super thanks closing for you
