### ISSUE TITLE
The cancel icon doesn't (always?) work

### ISSUE THREAD

**Issue by ghost** [linuxmint/mintupload#28]
Perhaps it was the way I had (mis?)entered credentials, but I found that the cancel button didn't work. Consequently I ended up with three of the test upload windows on screen at once. They disappeared only when they timed out.

Here's a picture of one of those upload windows:

![image](https://cloud.githubusercontent.com/assets/9998846/22273881/3a7d2198-e29b-11e6-8ed9-4fb686eef21f.png)

Mint 18.1 CInnamon x64. Mint Upload 4.0.9.

**Comment by clefebvre** [comment]
It cannot cancel the currently upload file, only the operation itself starting from the next file in the queue.
