### ISSUE TITLE
LM 22 Wilma: MintUpload not uploading files to FTP anymore

### ISSUE THREAD

**Issue by guillaumesoucy94** [linuxmint/mintupload#44]
Hello, 

I noticed since the upgrade to LM 22 Wilma on all my computers, MintUpload silently fails to upload files using FTP. No error message is provided on the Linux Mint GUI.

I don't know where to find the log on my machine or to activate the debug for MintUpload.

I joint a video screen capture showing what happen when attempting to upload a 250MB file.

Thanks, 

Guillaume

https://github.com/user-attachments/assets/af22683e-4514-408f-8a64-ce50893893d5

**Comment by clefebvre** [comment]
Fixed in 4.2.2
