### ISSUE TITLE
Closing the tray icon doesn't close the mintUpload window(s)

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/mintupload#5]
OS: Mint 16 "Petra" 32-bit
mintUpload 3.9.4

The "Quit" option from the mintUpload tray icon should close all open windows (related to https://github.com/linuxmint/mintupload/issues/4)

or...

the mintUpload's tray menu should have an option that allows closing all the mintUpload's chlidren/windows.

**Comment by tiwari85aman** [comment]
@kneekoo Sir, I have worked on this issue, and the fix i have done is capable of closing one particular "upload-manager" on clicking on "Quit" option from mintUpload tray icon.

**Comment by clefebvre** [comment]
It's not supposed to. The tray is its own process, distinct from the menu application.
