### ISSUE TITLE
Create new service allows empty name, spaces, special characters

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/mintupload#6]
OS: Mint 16 "Petra" 32-bit
mintUpload 3.9.4

File -> New -> Service name

Although you're advised against using spaces or special characters, they are not disallowed/rejected nor filtered. On top of that, you can even click OK without adding anything at all in the service name box.

![mintupload-name-only-spaces](https://f.cloud.github.com/assets/566306/1580885/b279f222-51c9-11e3-8899-c14aa6febd84.png)

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/mintupload/commit/a4bf16c3338b44801730093031a9bb95dd5f0ad3
