### ISSUE TITLE
Toolbar buttons not translated

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/mintupload#8]
OS: Mint 16 "Petra" 32-bit
mintUpload 3.9.4

New, Edit, Delete <- not in Launchpad for translation

**Comment by clefebvre** [comment]
Fixed by install language-packs for GNOME.

for instance, for French: 

apt install language-pack-gnome-fr language-pack-gnome-fr-base

**Comment by monsta** [comment]
Oh wow - I had no idea :smile:
